plt.figure()
plt.title('Local Search runtime (s) per test')
plt.plot(results_df['test'], results_df['ls_runtime'], marker='o')
plt.xticks(rotation=90)
plt.xlabel('Test')
plt.ylabel('Runtime (s)')
plt.show()

plt.figure()
plt.title('CSP runtime (s) per test')
plt.plot(results_df['test'], results_df['csp_runtime'], marker='o')
plt.xticks(rotation=90)
plt.xlabel('Test')
plt.ylabel('Runtime (s)')
plt.show()
